name: "Docs"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'swiftannotate/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'swiftannotate/**'

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: "Install poetry"
        env:
          POETRY_VERSION: '2.0.1'
        run: pipx install "poetry==${POETRY_VERSION}"

      - name: "Set up Python"
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Build MkDocs site
        run: |
          cd docs/
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force